### PR TITLE
Made native examples include kotest itself, if it exists in a sibling…

### PR DESCRIPTION
**Pull request by Kantis**
… directory

With this, we can make a code change in `kotest` and directly try it out without first having to publish the right stuff to `mavenLocal`, gradle will resolve it from the included build 🪄

### CODE REVIEW

**Comment by sksamuel** [comment]
what is this includeBuild thing ?

**Comment by Kantis** [comment]
It adds the includedBuild into the "build context". The neat thing is that it detects modules which match the groupId / artifactId of any dependency used in the build where the inclusion was made and substitutes the Maven dependency for w/e is built by the included build. Basically, it lets us build _this project) using the current commit of our checked out kotest repos , so we can easily try changes without needing to do the mavenLocal publishing

**Comment by sksamuel** [comment]
So as long as kotest and this directly are checked out in the same folder, it kinda combines them as a single project ?

**Comment by Kantis** [comment]
Yes, but it'll only build the parts of the main repo that this repo includes, so not a full build of every variant would be needed. And it only goes the direction of the includes, so if you're working in `/kotest` you'll only have the main repo

**Comment by sksamuel** [comment]
Nice :)

**Pull request merged**
